sonar.projectKey=portfolio-fullstack
sonar.projectName=Portfolio Fullstack
sonar.projectVersion=1.0

# Analyser uniquement le backend
sonar.sources=docker/backend

# Exclure JS/TS (trop lourd pour la RAM disponible) + node_modules
sonar.exclusions=**/node_modules/**,**/*.test.js,**/package-lock.json,**/*.js,**/*.ts

# Encodage
sonar.sourceEncoding=UTF-8
