apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: portfolio
type: Opaque
stringData:
  MONGO_ROOT_USER: admin
  MONGO_ROOT_PASSWORD: ChangeMe123
  MONGO_DB: portfolio
  MONGO_URI: "mongodb://admin:ChangeMe123@mongodb:27017/portfolio?authSource=admin"
